### PR TITLE
v2 ?

### PR DESCRIPTION
**Pull request by arthurdarcet**
We are using this library to do some server-side CSS processing, and it's great (thank you for your work!)

We do have a few requirements that aren't met though: we need to be able to parse data a bit more than getting the raw string value of the CSS rules.
Namely, we need to parse the `src: url(…) format(…)` rules from font-faces, and the `@import url(…);` rules.

This pull requests allows us to do this, by exposing the underlying scanner.Token objects instead of aggregating them in a string value.
I've also included a bunch of helper method that helps with processing strings.

I don't know if you are open to this kind of breaking changes - feel free to refuse the PR if need, just wanted to share what we've built on top of your library

### CODE REVIEW

**Comment by vanng822** [comment]
Thanks for helping. I just took a quick look and it looks like we only change how to store the value which resulting in 2 changes Selector.Text() and Value.Text() instead of SelectorText and Value?

Not sure how many people are using this I created this since I didn't find any css-parser then. I needed it for https://github.com/vanng822/go-premailer However we should bump up version to make sure not breaking any applications out there.

Not sure what is the best way to create v2?
possibly move everything new in /v2 and keep old one in the current structure? or what do you think?

**Comment by vanng822** [comment]
Or would it be enough to create a release version since this package is not really big and no need of fixing bug on older version :-D

**Comment by arthurdarcet** [comment]
Breaking changes: yes correct, the only two breaking changes are `.SelectorText -> .Selector.Text()`, and `.Value -> .Value.Text()`.

Versioning: there is no need to create another copy of the code in my opinion: git will take care of keeping the history available for you. Here I would simply merge this, then tag a `v1.0.0` to signify the breaking changes (no need to jump to v2 directly, v1 was never released)

**Comment by vanng822** [comment]
I release and tested it for my case. Seems working well.
Thank you for your contribution

**Pull request merged**
